import { useCallback, useState } from "react";
import { useNavigate } from "react-router-dom";
import useResume from "@/components/declarations/useResume";
import type { ResumeData } from "@/components/declarations/types";

export type PdfImportStatus = "idle" | "loading" | "success" | "error";

export interface UsePdfImportResult {
  status: PdfImportStatus;
  error: string | null;
  importedCount: number;
  importFromFile: (file: File) => Promise<void>;
  reset: () => void;
}

function countFilledFields(data: ResumeData): number {
  let count = 0;
  if (data.personalInfo.name) count++;
  if (data.personalInfo.title) count++;
  if (data.personalInfo.aboutMe) count++;
  if (data.personalInfo.email) count++;
  if (data.personalInfo.phoneNumber) count++;
  if (data.personalInfo.linkedIn) count++;
  if (data.personalInfo.github) count++;
  count += data.skills.length;
  count += data.workExperience.length;
  count += data.education.length;
  count += data.certifications.length;
  count += data.awards.length;
  count += data.languages.length;
  count += data.patents.length;
  count += data.projects.length;
  return count;
}

export function usePdfImport(): UsePdfImportResult {
  const { setResumeData } = useResume();
  const navigate = useNavigate();
  const [status, setStatus] = useState<PdfImportStatus>("idle");
  const [error, setError] = useState<string | null>(null);
  const [importedCount, setImportedCount] = useState(0);

  const importFromFile = useCallback(
    async (file: File) => {
      if (!file) return;
      if (file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf")) {
        setError("Please upload a valid PDF file.");
        setStatus("error");
        return;
      }
      if (file.size > 10 * 1024 * 1024) {
        setError("PDF is too large (max 10MB).");
        setStatus("error");
        return;
      }
      setStatus("loading");
      setError(null);
      try {
        const buffer = await file.arrayBuffer();
        // Dynamic import to keep pdfjs-dist out of initial bundle
        const { parseResumePdf } = await import("@/components/PdfImport/pdfParser");
        const parsed = await parseResumePdf(buffer);
        const filled = countFilledFields(parsed);
        if (filled === 0) {
          throw new Error("Could not find resume data in the PDF. Try a PDF generated by this app.");
        }
        setResumeData(parsed);
        // Persist so refresh keeps data
        try {
          localStorage.setItem("resumeData", JSON.stringify(parsed));
        } catch {
          // ignore
        }
        setImportedCount(filled);
        setStatus("success");
        // Navigate to resume builder after a short delay to show success state
        setTimeout(() => {
          navigate("/resume");
        }, 400);
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e));
        setStatus("error");
      }
    },
    [setResumeData, navigate],
  );

  const reset = useCallback(() => {
    setStatus("idle");
    setError(null);
    setImportedCount(0);
  }, []);

  return { status, error, importedCount, importFromFile, reset };
}

export default usePdfImport;
